# Site settings
title: DROTS
email: joe@databrew.cc
url: http://droneots.com
baseurl:
description: #'We came asking if drones can be used to deliver healthcare in a really remote setting... We left wondering how quality healthcare can possibly be delivered without them.'

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: DROTS

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCtiIVN4cHxWbcJVinepUY3Q
  - title: twitter
    url: https://twitter.com/joethebrew
  - title: facebook
    url: https://www.facebook.com/josephbrew

# Build settings
markdown: kramdown
permalink: pretty
